### ISSUE TITLE
Need xcode 10 and swift 4.2 support

### ISSUE THREAD

**Issue by Mahesh160393** [kkontus/SwiftCheckboxDialogCocoapod#3]
@kkontus I am using this library from last one year and  in multiple places in one project..now it not support for xcode 10..So can you please provide me support for xcode 10 and if possible swift 4.2. I am kind of stuck here so I need your support as soon as possible..

**Comment by kkontus** [comment]
I'll try to update it when I catch some time, but in the meantime feel free to take this code and update it yourself until I update it

**Comment by kkontus** [comment]
@Mahesh160393 it should be released now, hope it all works

**Comment by Mahesh160393** [comment]
@kkontus thank you for reply and update.
